### PR TITLE
Slot website verification fix

### LINKED ISSUE #104: creating an ad slot overrides the previous `verifiedForce`

### PR DESCRIPTION
**Pull request by IvoPaunov**
* fixed `verifiedForce` overwrite when ad slot with same website submitted closes #104 
* websites verified by others issue returned with publisher slots
* catch on .well-known check
* lint fix
* return passback units with slot reponse

### CODE REVIEW

File: routes/adSlots.js [hunk 1]
```diff
@@ -247,7 +268,7 @@ function getWebsiteIssues(websiteRecord, existingFromOthers) {
 	if (!websiteRecord.verifiedOwnership) {
 		issues.push('SLOT_ISSUE_OWNERSHIP_NOT_VERIFIED')
 	}
-	if (existingFromOthers && existingFromOthers.length) {
+	if (existingFromOthers) {
```
Comment (Ivshti) [inline routes/adSlots.js]: why?

Comment (IvoPaunov) [reply routes/adSlots.js]: it's changed to `.count()`
