### PR TITLE
Correctly retrieve root domain

### LINKED ISSUE #162: publisher verification: root name check is wrong
e.g. https://www.geographia.com.br/

in this case we interpret com.br as a root name and not geographia.com.br

### PR DESCRIPTION
**Pull request by simzzz**
fixes #162

### CODE REVIEW

File: lib/singleElementTlds.js [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+	'ws',
+	'ink',
+	'work',
+	'design',
+	'london',
+	'today',
+	'dev',
+	'company',
+	'pro',
+	'solutiuons',
```
Comment (Ivshti) [inline lib/singleElementTlds.js:40]: typo?

File: lib/singleElementTlds.js [hunk 2]
```diff
@@ -0,0 +1,41 @@
+module.exports = [
```
Comment (Ivshti) [inline lib/singleElementTlds.js:1]: where did you get that list from? doesn't look complete

File: lib/publisherVerification.js [hunk 3]
```diff
@@ -36,15 +37,29 @@ async function getAccount(addr) {
 	} else return response
 }
 
+function getRootName(hostname) {
+	let split_hostname = hostname.split('.')
```
Comment (Ivshti) [inline lib/publisherVerification.js:41]: use camelCase naming convention

**Review by Ivshti — CHANGES_REQUESTED** [review]

**Review by Ivshti — APPROVED** [review]

File: lib/publisherVerification.js [hunk 4]
```diff
@@ -255,3 +273,5 @@ module.exports = {
 	isHostnameBlacklisted,
 	BLACKLISTED_HOSTNAMES,
 }
+
+console.log(getRootName('www.mysite.github.io'))
```
Comment (Ivshti) [inline lib/publisherVerification.js:277]: test code forgotten

**Review by Ivshti — CHANGES_REQUESTED** [review]

**Review by Ivshti — APPROVED** [review]
